version: "3.7"

networks:
  sppe_network:
    name: ${PROJECT_NAME:-sppe}-prod_network
    driver: bridge

volumes:
  dbdatadir:
    name: ${PROJECT_NAME:-sppe}-prod_dbdatadir
  sftp_dir:
    name: ${PROJECT_NAME:-sppe}-prod_sftp_dir


services:

  sftp:
    build:
      context: ./docker/sftp
    container_name: ${PROJECT_NAME:-sppe}-prod_sftp
    ports:
       - ${SPPE_SFTP:-2222}:22
    networks:
      - sppe_network
    volumes:
       - sftp_dir:/var/sftp
       - ./docker/sftp/sshd_config:/etc/ssh/sshd_config:ro

  web:
    image: nginx:1.19.0-alpine
    container_name: ${PROJECT_NAME:-sppe}-prod_webfront
    volumes:
       - ./app:/app
       - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
       - ${SPPE_HTTP:-8080}:80
    networks:
      - sppe_network
    depends_on:
      - php

  php:
    image: bhrneedone/php-symfony-pgsql:latest
    container_name: ${PROJECT_NAME:-sppe}-prod_php
    networks:
      - sppe_network
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
      - db

  php-cron:
    image: bhrneedone/php-symfony-pgsql:latest
    container_name: ${PROJECT_NAME:-sppe}-prod_php-cron
    networks:
      - sppe_network
    command: sh -c "crontab /crontab && crond -f -L /var/log/cron.log"
    volumes:
      - ./app:/app
      - ./docker/php/crontab:/crontab
      - sftp_dir:/var/sftp
    working_dir: /app
    depends_on:
      - db

  db:
    image: postgres:13.2-alpine
    container_name: ${PROJECT_NAME:-sppe}-prod_db
    restart: always
    environment:
      POSTGRES_USER: ${SPPE_DB_USER:-user}
      POSTGRES_PASSWORD: ${SPPE_DB_PASSWORD:-pass}
      POSTGRES_DB: ${SPPE_DB_NAME:-sppe}
    volumes:
      - dbdatadir:/var/lib/postgresql/data/
    networks:
      - sppe_network

