version: "3.7"

networks:
  sppe_network:
    name: ${PROJECT_NAME:-sppe}-dev_network
    driver: bridge

volumes:
  dbdatadir:
    name: ${PROJECT_NAME:-sppe}-dev_dbdatadir
  sftp_dir:
    name: ${PROJECT_NAME:-sppe}-dev_sftp_dir

services:

  web:
    image: nginx:1.19.0-alpine
    container_name: ${PROJECT_NAME:-sppe}-dev_webfront
    volumes:
       - ./app:/app
       - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
       - ${SPPE_HTTP:-8080}:80
    networks:
      - sppe_network
    depends_on:
      - php

  php:
    image: bhrneedone/php-symfony-pgsql:latest
    container_name: ${PROJECT_NAME:-sppe}-dev_php
    networks:
      - sppe_network
    volumes:
      - ./app:/app
      - sftp_dir:/var/sftp
    working_dir: /app
    depends_on:
      - db

  db:
    image: postgres:13.2-alpine
    container_name: ${PROJECT_NAME:-sppe}-dev_db
    restart: always
    environment:
      POSTGRES_USER: ${SPPE_DB_USER:-user}
      POSTGRES_PASSWORD: ${SPPE_DB_PASSWORD:-pass}
      POSTGRES_DB: ${SPPE_DB_NAME:-sppe}
    volumes:
      - dbdatadir:/var/lib/postgresql/data/
    networks:
      - sppe_network

  dbtest:
    image: postgres:13.2-alpine
    container_name: ${PROJECT_NAME:-sppe}-dev_dbtest
    restart: always
    environment:
      POSTGRES_USER: ${SPPE_DB_USER:-user}
      POSTGRES_PASSWORD: ${SPPE_DB_PASSWORD:-pass}
      POSTGRES_DB: ${SPPE_DB_NAME:-sppe}
    networks:
      - sppe_network

  adminer:
    image: adminer
    container_name: ${PROJECT_NAME:-sppe}-dev_adminer
    restart: always
    ports:
      - ${SPPE_ADMINER_HTTP:-8089}:8080
    networks:
      - sppe_network
    depends_on:
      - db
      - dbtest

